name: arcticdb
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  - pkg-config
  - gtest
  - gflags
  - doxygen
  - grpcio
  - grpcio-tools
  - protobuf
  # Host dependencies
  - boost-cpp
  - krb5
  - lz4-c
  - double-conversion
  - libevent
  - libmongocxx
  - zstd
  - pybind11
  - pcre
  - cyrus-sasl
  - aws-sdk-cpp
  - prometheus-cpp
  - libprotobuf < 4
  - bitmagic
  - spdlog
  # Incompatibility with fmt last version
  - fmt < 10
  # folly has no ABI compatibility from one commit to another.
  # Hence we have to use the exact same version of folly on both build setup.
  # This is the common oldest version of folly on vcpkg and conda-forge
  - folly==2023.05.22.00
  # Vendored build dependencies (see `cpp/thirdparty`)
  # Versions must be kept in sync
  - xxhash
  - semimap
  - robin_hood
  - rapidcheck
  - msgpack-c
  - recycle
  # Matches the version of lmdb and lmdbxx as vendored
  # via submodules.
  - lmdb==0.9.22
  - lmdbxx==0.9.14
  - libarrow
  - libiconv
  - aws-c-s3
  # Python dependences
  - python =3.10 # Python 3.11 requires protobuf>=4
  - numpy
  - pandas < 2
  - pytest
  - boto3
  - werkzeug
  - moto
  - pytest-server-fixtures
  - msgpack-python
  # Pinned to avoid test disruption (in phase with the pin in setup.cfg)
  # See: https://github.com/man-group/ArcticDB/pull/291
  - hypothesis < 6.73
  - pytest-sugar

